version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - ./VOZ_neww/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vozdb
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - voz_dash
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: sh -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000" 
    volumes:
      - ./api:/app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/vozdb
    networks:
      - voz_dash

  scrapy:
    build: ./VOZ_neww
    command: ["/start.sh", "scrapy", "crawl", "demospider"]
    volumes:
      - ./VOZ_neww:/app
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_healthy
    networks:
      - voz_dash
       
networks:
  voz_dash:
    driver: bridge